default: &default
  adapter: postgresql
  encoding: utf8

test:
  <<: *default
  database: is_test_test
  pool: 16
  timeout: 12000

development:
  <<: *default
  database: is_test_development
  pool: 16
  timeout: 12000

beta:
  <<: *default

stage:
  <<: *default

production:
  <<: *default
  database: is_test_production
  pool: 16
  timeout: 12000
